[project]
name = "mustfile"
version = "0.2.0"

[env]
RUST_LOG = "warn"

[env.release]
RUST_LOG = "error"

[recipe.build]
type    = "shell"
cache   = "hash"
inputs  = ["crates/*/src/**/*.rs", "crates/*/Cargo.toml", "Cargo.toml"]
outputs = ["target/debug/must"]
script  = "cargo build"

[recipe.release]
type    = "shell"
cache   = "hash"
inputs  = ["crates/*/src/**/*.rs", "crates/*/Cargo.toml", "Cargo.toml"]
outputs = ["target/release/must"]
deps    = ["build"]
script  = "cargo build --release"

[recipe.test]
type   = "shell"
deps   = ["build"]
phony  = true
script = "cargo test"

[recipe.lint]
type   = "shell"
phony  = true
script = "cargo clippy -- -D warnings"

[recipe.fmt]
type   = "shell"
phony  = true
script = "cargo fmt --check"

[recipe.ci]
type   = "shell"
deps   = ["fmt", "lint", "test"]
phony  = true
script = "echo 'CI passed'"

[recipe.clean]
type   = "shell"
phony  = true
script = "cargo clean"
