name: Question
description: Ask a question about using mustfile
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're happy to help!
  - type: textarea
    id: question
    attributes:
      label: Your Question
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What have you tried? What are you trying to achieve?
