[package]
name = "must-recipe-precompiled"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
must-core = { path = "../must-core" }
must-cache = { path = "../must-cache" }
sha2.workspace = true
hex.workspace = true
ureq = "2"

[dev-dependencies]
tempfile.workspace = true
