[package]
name = "must-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "must"
path = "src/main.rs"

[dependencies]
must-core = { path = "../must-core" }
must-config = { path = "../must-config" }
must-graph = { path = "../must-graph" }
must-engine = { path = "../must-engine" }
must-cache = { path = "../must-cache" }
must-toolchain = { path = "../must-toolchain" }
must-recipe-shell = { path = "../must-recipe-shell" }
must-recipe-rust = { path = "../must-recipe-rust" }
must-recipe-go = { path = "../must-recipe-go" }
must-recipe-cc = { path = "../must-recipe-cc" }
must-recipe-ts = { path = "../must-recipe-ts" }
must-recipe-py = { path = "../must-recipe-py" }
must-recipe-zig = { path = "../must-recipe-zig" }
must-recipe-docker = { path = "../must-recipe-docker" }
must-recipe-java = { path = "../must-recipe-java" }
must-recipe-kotlin = { path = "../must-recipe-kotlin" }
must-recipe-swift = { path = "../must-recipe-swift" }
must-recipe-dart = { path = "../must-recipe-dart" }
must-recipe-dotnet = { path = "../must-recipe-dotnet" }
must-recipe-ruby = { path = "../must-recipe-ruby" }
must-recipe-elixir = { path = "../must-recipe-elixir" }
must-recipe-flutter = { path = "../must-recipe-flutter" }
must-recipe-nim = { path = "../must-recipe-nim" }
must-recipe-precompiled = { path = "../must-recipe-precompiled" }
must-import = { path = "../must-import" }
must-plugin = { path = "../must-plugin" }
tokio = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
glob = { workspace = true }
serde = { workspace = true }
notify = "8"
num_cpus = "1"
serde_json = "1"
indicatif = "0.18"
reqwest = { version = "0.13", features = ["rustls"], default-features = false }

[dev-dependencies]
tempfile.workspace = true
