[package]
name = "must-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "must"
path = "src/main.rs"

[dependencies]
must-core = { path = "../must-core" }
must-config = { path = "../must-config" }
must-graph = { path = "../must-graph" }
must-engine = { path = "../must-engine" }
must-recipe-shell = { path = "../must-recipe-shell" }
must-recipe-rust = { path = "../must-recipe-rust" }
must-cache = { path = "../must-cache" }
clap.workspace = true
glob.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
